PHP_VER=		74

PLUGIN_NAME=		proxy-useracl
PLUGIN_VERSION=		1.7.1
PLUGIN_REVISION=
PLUGIN_COMMENT=		Group & User Squid ACL
PLUGIN_DEPENDS=
PLUGIN_MAINTAINER=	a.shursha@smart-soft.ru
PLUGIN_WWW=		http://smart-soft.ru
PLUGIN_ENCODE=		yes
PLUGIN_NOENCODE=	src/opnsense/mvc/app/models/SmartSoft/ProxyUserACL/

.include "../../Mk/plugins.mk"
