PHP_VER=		74

PLUGIN_NAME=		web-proxy-sso
PLUGIN_VERSION=		2.3
PLUGIN_REVISION=
PLUGIN_COMMENT=		Kerberos authentication module
PLUGIN_DEPENDS=		msktutil cyrus-sasl-gssapi php${PHP_VER}-pear-Net_DNS2
PLUGIN_MAINTAINER=	a.shursha@smart-soft.ru
PLUGIN_WWW=		http://smart-soft.ru


.include "../../Mk/plugins.mk"
